import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, String> _fr = {
    'app_name': 'TicketScan',
    'ok': 'OK',
    'cancel': 'Annuler',
    'save': 'Enregistrer',
    'delete': 'Supprimer',
    'delete_ticket': 'Supprimer le ticket',
    'edit': 'Modifier',
    'search': 'Rechercher',
    'sign_in': 'Se connecter',
    'sign_up': 'S\'inscrire',
    'no_account_prompt': 'Pas encore de compte ? S\'inscrire',
    'already_account_prompt': 'Déjà un compte ? Se connecter',
    'sign_out': 'Se déconnecter',
    'email': 'Email',
    'password': 'Mot de passe',
    'tickets': 'Tickets',
    'search_tickets': 'Rechercher un ticket',
    'scan': 'Scanner',
    'profile': 'Profil',
    'home': 'Accueil',
    'quick_search': 'Recherche rapide',
    'search_hint': 'Tapez un nom de magasin...',
    'recent_searches': 'Recherches récentes',
    'no_recent_searches': 'Aucune recherche récente',
    'my_tickets': 'Mes Tickets',
    'registered_tickets': 'Tickets enregistrés',
    'free_offer_limit': 'Offre gratuite : 3 tickets max',
    'premium_ticket_access': 'Tickets illimités',
    'export_pdf': 'Exporter PDF',
    'ticket_actions': 'Actions du ticket',
    'no_tickets': 'Aucun ticket enregistré',
    'ticket_details': 'Détails du ticket',
    'store_name': 'Magasin',
    'date': 'Date d\'achat',
    'total_amount': 'Montant total',
    'products': 'Articles',
    'warranty': 'Garantie',
    'warranty_end_date': 'Fin de garantie',
    'settings': 'Paramètres',
    'privacy_policy': 'Politique de confidentialité',
    'about': 'À propos',
    'upgrade_premium': 'Passer au Premium',
    'premium_plan': 'Version Premium',
    'best_value_badge': 'Meilleure valeur',
    'unlimited_scans': 'Scans illimités',
    'monthly_limit': 'Limite de 3 tickets atteinte.',
    'later': 'Plus tard',
    'per_month': '/ Mois',
    'per_year': '/ An',
    'limit_reached_msg': 'Vous avez utilisé vos 3 tickets gratuits.',
    'limit_reached_sub':
        'Votre accès est limité. Abonnez-vous dès maintenant pour bénéficier d\'un accès complet.',
    'subscribe': 'Souscrire',
    'terms_of_service': 'Conditions d\'utilisation',
    'premium_yearly_detail': 'Abonnement annuel',
    'premium_monthly_detail': 'Abonnement mensuel',
    'manage_unlimited': 'Gérez tous vos tickets sans limite',
    'yearly': 'Annuel',
    'monthly': 'Mensuel',
    'premium_unlock_msg': 'Accès illimité à toutes les fonctions',
    'payment_secure_note_google_play':
        'Le paiement sera traité de manière sécurisée par Google Play. Vous pouvez annuler à tout moment dans vos paramètres Google Play.',
    'payment_secure_note_app_store':
        'Le paiement sera traité de manière sécurisée par l\'App Store. Vous pouvez annuler à tout moment dans vos réglages.',
    'payment_button_google_play': 'Payer via Google Play',
    'payment_button_app_store': 'Payer via l\'App Store',
    'payment_button_unsupported': 'Paiement non disponible',
    'payment_service_unavailable_google_play':
        'Google Play n\'est pas disponible pour le moment. Veuillez réessayer.',
    'payment_service_unavailable_app_store':
        'L\'App Store n\'est pas disponible pour le moment. Veuillez réessayer.',
    'payment_platform_unsupported':
        'Le paiement d\'abonnement n\'est pas disponible sur cette plateforme.',
    'payment_error_generic':
        'Le paiement n\'a pas pu aboutir. Veuillez réessayer.',
    'premium_activated': 'Félicitations ! Vous êtes maintenant Premium 🚀',
    'live_env': 'Environnement en direct',
    'premium_banner_msg': 'Passez à la version Premium',
    'contact_support': 'Contacter le support',
    'delete_account': 'Supprimer mon compte',
    'delete_account_warning':
        'Attention : cette action est irréversible. Toutes vos données seront supprimées.',
    'dark_mode': 'Thème',
    'theme_light': 'Clair',
    'theme_dark': 'Sombre',
    'theme_system': 'Système',
    'language': 'Langue',
    'language_french': 'Français',
    'language_english': 'English',
    'forgot_password': 'Mot de passe oublié ?',
    'forgot_email': 'Identifiant / Email oublié ?',
    'reset_password': 'Réinitialiser le mot de passe',
    'send_reset_link': 'Envoyer le lien de réinitialisation',
    'new_password': 'Nouveau mot de passe',
    'confirm_password': 'Confirmer le mot de passe',
    'passwords_dont_match': 'Les mots de passe ne correspondent pas',
    'password_reset_success':
        'Votre mot de passe a été réinitialisé avec succès !',
    'reset_link_sent':
        'Un lien de réinitialisation a été envoyé à votre adresse email.',
    'forgot_email_title': 'Email oublié ?',
    'forgot_email_content':
        'Pour retrouver votre compte, nous vous invitons à :\n\n1. Rechercher "TicketScan" dans vos boîtes mail pour retrouver l\'email d\'inscription.\n\n2. Si vous avez un abonnement Premium actif, contactez le support avec votre justificatif pour retrouver votre compte.',
    'contact_support_button': 'Contacter le support',
    // Auth error messages
    'error_title': 'Erreur de connexion',
    'error_invalid_credentials':
        'Email ou mot de passe incorrect. Veuillez vérifier vos identifiants et réessayer.',
    'error_email_not_confirmed':
        'Votre adresse email n\'a pas encore été confirmée. Veuillez vérifier votre boîte de réception.',
    'error_user_not_found': 'Aucun compte trouvé avec cette adresse email.',
    'error_weak_password':
        'Le mot de passe doit contenir au moins 6 caractères.',
    'error_email_taken': 'Un compte existe déjà avec cette adresse email.',
    'error_too_many_requests':
        'Trop de tentatives. Veuillez patienter quelques minutes avant de réessayer.',
    'error_network':
        'Erreur de connexion réseau. Vérifiez votre connexion internet et réessayez.',
    'error_generic': 'Une erreur est survenue. Veuillez réessayer.',
    'error_signup_title': 'Erreur d\'inscription',
    // Auth success messages
    'success_email_not_confirmed_title': 'Email non confirmé',
    'success_email_not_confirmed_msg':
        'Veuillez vérifier votre boîte mail et cliquer sur le lien de confirmation.',
    'success_account_created_title': 'Compte créé !',
    'success_account_created_msg':
        'Un email de confirmation vous a été envoyé.',
    'no_warranty_title': 'Aucun produit sous garantie',
    'edit_ticket': 'Modifier le ticket',
    'no_warranty_banner':
        'Aucun produit garanti — le ticket ne sera pas enregistré',
    'no_warranty_msg':
        'Ce ticket ne présente aucun produit sous garantie. Il ne sera pas enregistré : sans produit garanti, il est inutile pour le suivi des garanties. Activez la garantie sur au moins un produit pour le conserver, ou abandonnez ce scan.',
    'no_warranty_edit_msg':
        'Ce ticket ne peut pas être modifié sans produit sous garantie. La modification ne sera pas enregistrée. Activez la garantie sur au moins un produit pour conserver le ticket.',
    'delete_invalid_ticket': 'Supprimer le ticket',
    'ticket_deleted': 'Ticket supprimé',
    'abandon_scan': 'Abandonner le scan',
    'edit_warranty': 'Modifier la garantie',
    'verification_title': 'Vérification',
    'date_label': 'Date (JJ/MM/AAAA)',
    'warranty_years_label': 'Garantie (années)',
    'edit_products_warranty': 'Modifier les produits & Garantie :',
    'no_products_detected': 'Aucun produit détecté',
    'product_hint': 'Produit',
    'price_hint': 'Prix',
    'error_image': 'Erreur image',
    'error_prefix': 'Erreur : ',
    'invalid_date_format': 'Format de date invalide',
    'restore': 'Restaurer',
    'share': 'Partager',
    'expired': 'Expiré',
    'total': 'Total',
    'filters_soon': 'Bientôt disponible',
    'generic_error': 'Erreur',
    'no_results': 'Aucun résultat trouvé',
    'scan_first_ticket': 'Scannez votre premier ticket',
    'scan_soon': 'Scanner bientôt',
    'scan_ticket': 'Scanner un ticket',
    'scan_error_title': 'Erreur de scan',
    'scan_not_a_receipt':
        'Cette photo ne semble pas montrer un ticket de caisse. Réessaie en cadrant bien le ticket, à plat et bien éclairé.',
    'scan_access_denied': 'Accès refusé',
    'scan_invalid_request': 'Requête invalide',
    'scan_service_unavailable':
        'Service de reconnaissance indisponible, réessaie dans un instant',
    'scan_server_error': 'Erreur serveur',
    'scan_multi_image_error': 'Erreur lors de l’analyse de plusieurs images',
    'scan_technical_error':
        'Une erreur technique est survenue pendant le scan.',
    'scan_unexpected_error': 'Une erreur inattendue est survenue.',
    'scan_save_error': 'Impossible d’enregistrer le ticket. Réessaie.',
    'scan_quota_exceeded': 'Limite de scans gratuits atteinte.',
    'delete_ticket_warning': 'Ce ticket sera supprimé définitivement.',
    'app_version': 'Version',
    'welcome_title': 'Bienvenue !',
    'welcome_subtitle': 'Gardez vos tickets et garanties\nau même endroit.',
    'scan_ticket_action': 'Scanner un ticket',
    'choose_image_action': 'Choisir une image',
    'security_title': 'Vos tickets en toute sécurité',
    'security_description':
        'Prenez en photo vos reçus, notre IA extrait les informations et vous aide à gérer vos garanties.',
    'see_all': 'Voir tout',
    'tickets_label': 'Tickets',
    'tickets_remaining': 'tickets restants',
    'unlimited': 'Illimité',
    'premium_access': 'Accès Premium',
    'premium_active': 'Actif',
    'full_access': 'Accès complet',
    'upgrade_short': 'Passez à',
    'tickets_free': 'Tickets\ngratuit',
    'products_under_warranty': 'Produits\nsous garantie',
    'under_warranty': 'sous garantie',
    'alerts_upcoming': 'Alerte(s)\nà venir',
    'upcoming': 'à venir',
    'premium_features': 'Plus de\nfonctionnalités',
    'premium_description':
        'Tickets illimités, export PDF/CSV, extension de garantie et alertes.',
    'menu': 'Menu',
    'alerts': 'Notifications',
    'my_account': 'Mon compte',
    'notifications': 'Notifications',
    'help': 'Aide',
    'free': 'GRATUIT',
    'premium_badge': 'PREMIUM',
    'manage_subscription': 'Gérer mon abonnement',
    'subscription': 'Abonnement',
    'premium_title': 'Profil Premium',
    'premium_active_status': 'Votre abonnement est actif',
    'premium_status': 'Statut :',
    'active': 'Actif',
    'premium_member': 'Membre Premium',
    'premium_features_list_title': 'Vos avantages Premium',
    'feat_unlimited_tickets': 'Tickets illimités',
    'feat_export': 'Export PDF/CSV',
    'feat_reminders': 'Rappels de garantie',
    'feat_warranty': 'Extension de garantie',
    'current_plan': 'Forfait actuel',
    'version_page_title': 'Version de l\'application',
    'app_info_description':
        'TicketScan vous aide à garder vos tickets et garanties au même endroit.',
    'support_title': 'Contact support',
    'support_description':
        'Une question ou un problème ? Notre équipe vous répond par email.',
    'write_us': 'Écrivez-nous',
    'tickets_short': 'Mes tickets',
    'alerts_title': 'Notifications',
    'no_alerts_title': 'Aucune alerte à venir',
    'no_alerts_description': 'Vos prochaines échéances apparaîtront ici.',
    'warranty_until': 'Garantie jusqu\'au',
    'account': 'Compte',
    'pdf_warranty_certificate': 'ATTESTATION DE GARANTIE',
    'pdf_store': 'Magasin',
    'pdf_purchase_date': 'Date d\'achat',
    'pdf_category': 'Catégorie',
    'pdf_total_amount': 'MONTANT TOTAL',
    'pdf_warranty_valid_until': 'GARANTIE VALIDE JUSQU\'AU :',
    'pdf_items_detail': 'DÉTAIL DES ARTICLES',
    'pdf_warrantied': 'Garanti',
    'pdf_purchase_proof': 'PREUVE D\'ACHAT (PHOTO)',
    'pdf_footer':
        'Document généré par l\'application TicketScan - Gardez vos preuves d\'achat en sécurité.',
    'pdf_preview': 'Aperçu du PDF',
  };

  static const Map<String, String> _en = {
    'app_name': 'TicketScan',
    'ok': 'OK',
    'cancel': 'Cancel',
    'save': 'Save',
    'delete': 'Delete',
    'delete_ticket': 'Delete ticket',
    'edit': 'Edit',
    'search': 'Search',
    'sign_in': 'Sign in',
    'sign_up': 'Sign up',
    'no_account_prompt': 'No account yet? Sign up',
    'already_account_prompt': 'Already have an account? Sign in',
    'sign_out': 'Sign out',
    'email': 'Email',
    'password': 'Password',
    'tickets': 'Tickets',
    'search_tickets': 'Search a ticket',
    'scan': 'Scan',
    'profile': 'Profile',
    'home': 'Home',
    'quick_search': 'Quick search',
    'search_hint': 'Type a store name...',
    'recent_searches': 'Recent searches',
    'no_recent_searches': 'No recent searches',
    'my_tickets': 'My Tickets',
    'registered_tickets': 'Tickets registered',
    'free_offer_limit': 'Free plan: 3 tickets max',
    'premium_ticket_access': 'Unlimited tickets',
    'export_pdf': 'Export PDF',
    'ticket_actions': 'Ticket actions',
    'no_tickets': 'No tickets saved',
    'ticket_details': 'Ticket details',
    'store_name': 'Store',
    'date': 'Purchase date',
    'total_amount': 'Total amount',
    'products': 'Products',
    'warranty': 'Warranty',
    'warranty_end_date': 'Warranty end date',
    'settings': 'Settings',
    'privacy_policy': 'Privacy Policy',
    'about': 'About',
    'upgrade_premium': 'Upgrade to Premium',
    'premium_plan': 'Premium Version',
    'best_value_badge': 'Best value',
    'unlimited_scans': 'Unlimited scans',
    'monthly_limit': '3 tickets limit reached.',
    'later': 'Later',
    'per_month': '/ Month',
    'per_year': '/ Year',
    'limit_reached_msg': 'You have used your 3 free tickets.',
    'limit_reached_sub':
        'Your access is limited. Subscribe now to enjoy full access.',
    'subscribe': 'Subscribe',
    'terms_of_service': 'Terms of Service',
    'premium_yearly_detail': 'Yearly subscription',
    'premium_monthly_detail': 'Monthly subscription',
    'manage_unlimited': 'Manage all your tickets without limit',
    'yearly': 'Yearly',
    'monthly': 'Monthly',
    'premium_unlock_msg': 'Unlimited access to all features',
    'payment_secure_note_google_play':
        'Payment is securely processed by Google Play. You can cancel anytime in your Google Play settings.',
    'payment_secure_note_app_store':
        'Payment is securely processed by the App Store. You can cancel anytime in your Settings.',
    'payment_button_google_play': 'Pay with Google Play',
    'payment_button_app_store': 'Pay with the App Store',
    'payment_button_unsupported': 'Payment unavailable',
    'payment_service_unavailable_google_play':
        'Google Play is not available right now. Please try again.',
    'payment_service_unavailable_app_store':
        'The App Store is not available right now. Please try again.',
    'payment_platform_unsupported':
        'Subscription payment is not available on this platform.',
    'payment_error_generic':
        'The payment could not be completed. Please try again.',
    'premium_activated': 'Congratulations! You are now Premium 🚀',
    'live_env': 'Live environment',
    'premium_banner_msg': 'Upgrade to Premium version',
    'contact_support': 'Contact Support',
    'delete_account': 'Delete my account',
    'delete_account_warning':
        'Warning: this action is irreversible. All your data will be deleted.',
    'dark_mode': 'Theme',
    'theme_light': 'Light',
    'theme_dark': 'Dark',
    'theme_system': 'System',
    'language': 'Language',
    'language_french': 'French',
    'language_english': 'English',
    'forgot_password': 'Forgot password?',
    'forgot_email': 'Forgot Email?',
    'reset_password': 'Reset Password',
    'send_reset_link': 'Send Reset Link',
    'new_password': 'New Password',
    'confirm_password': 'Confirm Password',
    'passwords_dont_match': 'Passwords do not match',
    'password_reset_success': 'Your password has been successfully reset!',
    'reset_link_sent':
        'A password reset link has been sent to your email address.',
    'forgot_email_title': 'Forgot Email?',
    'forgot_email_content':
        'To find your account, we suggest you:\n\n1. Search for "TicketScan" in your email inboxes to find the registration email.\n\n2. If you have an active Premium subscription, contact support with your proof of purchase to locate your account.',
    'contact_support_button': 'Contact Support',
    // Auth error messages
    'error_title': 'Sign in error',
    'error_invalid_credentials':
        'Incorrect email or password. Please check your credentials and try again.',
    'error_email_not_confirmed':
        'Your email address has not been confirmed yet. Please check your inbox.',
    'error_user_not_found': 'No account found with this email address.',
    'error_weak_password': 'Password must be at least 6 characters long.',
    'error_email_taken': 'An account already exists with this email address.',
    'error_too_many_requests':
        'Too many attempts. Please wait a few minutes before trying again.',
    'error_network':
        'Network connection error. Please check your internet connection and try again.',
    'error_generic': 'An error occurred. Please try again.',
    'error_signup_title': 'Sign up error',
    // Auth success messages
    'success_email_not_confirmed_title': 'Email not confirmed',
    'success_email_not_confirmed_msg':
        'Please check your inbox and click the confirmation link.',
    'success_account_created_title': 'Account created!',
    'success_account_created_msg': 'A confirmation email has been sent to you.',
    'no_warranty_title': 'No product under warranty',
    'edit_ticket': 'Edit ticket',
    'no_warranty_banner':
        'No product under warranty — the ticket will not be saved',
    'no_warranty_msg':
        'This receipt has no product under warranty. It will not be saved: without a warranty product, it is useless for warranty tracking. Enable the warranty on at least one product to keep it, or abandon this scan.',
    'no_warranty_edit_msg':
        'This ticket cannot be updated without a product under warranty. The changes will not be saved. Enable the warranty on at least one product to keep the ticket.',
    'delete_invalid_ticket': 'Delete ticket',
    'ticket_deleted': 'Ticket deleted',
    'abandon_scan': 'Abandon scan',
    'edit_warranty': 'Edit warranty',
    'verification_title': 'Verification',
    'date_label': 'Date (DD/MM/YYYY)',
    'warranty_years_label': 'Warranty (years)',
    'edit_products_warranty': 'Edit products & Warranty:',
    'no_products_detected': 'No products detected',
    'product_hint': 'Product',
    'price_hint': 'Price',
    'error_image': 'Image error',
    'error_prefix': 'Error: ',
    'invalid_date_format': 'Invalid date format',
    'restore': 'Restore',
    'share': 'Share',
    'expired': 'Expired',
    'total': 'Total',
    'filters_soon': 'Coming soon',
    'generic_error': 'Error',
    'no_results': 'No results found',
    'scan_first_ticket': 'Scan your first receipt',
    'scan_soon': 'Scan coming soon',
    'scan_ticket': 'Scan a receipt',
    'scan_error_title': 'Scan error',
    'scan_not_a_receipt':
        'This photo does not appear to show a receipt. Try again with the receipt fully in frame, flat, and well lit.',
    'scan_access_denied': 'Access denied',
    'scan_invalid_request': 'Invalid request',
    'scan_service_unavailable':
        'Recognition service unavailable. Please try again in a moment.',
    'scan_server_error': 'Server error',
    'scan_multi_image_error': 'Error analyzing multiple images.',
    'scan_technical_error': 'A technical error occurred during the scan.',
    'scan_unexpected_error': 'An unexpected error occurred.',
    'scan_save_error': 'Unable to save the receipt. Please try again.',
    'scan_quota_exceeded': 'Free scan limit reached.',
    'delete_ticket_warning': 'This ticket will be permanently deleted.',
    'app_version': 'Version',
    'welcome_title': 'Welcome!',
    'welcome_subtitle': 'Keep your tickets and warranties\nin one place.',
    'scan_ticket_action': 'Scan a ticket',
    'choose_image_action': 'Choose an image',
    'security_title': 'Your tickets, safely stored',
    'security_description':
        'Take photos of your receipts, our AI extracts the information and helps you manage your warranties.',
    'see_all': 'See all',
    'tickets_label': 'Tickets',
    'tickets_remaining': 'tickets remaining',
    'unlimited': 'Unlimited',
    'premium_access': 'Premium access',
    'premium_active': 'Active',
    'full_access': 'Full access',
    'upgrade_short': 'Upgrade to',
    'tickets_free': 'Tickets\n(free)',
    'products_under_warranty': 'Products\nunder warranty',
    'under_warranty': 'under warranty',
    'alerts_upcoming': 'Alerts\nupcoming',
    'upcoming': 'upcoming',
    'premium_features': 'More\nfeatures',
    'premium_description':
        'Unlimited tickets, PDF/CSV export, warranty extensions and alerts.',
    'menu': 'Menu',
    'alerts': 'Notifications',
    'alerts_title': 'Notifications',
    'no_alerts_title': 'No upcoming alerts',
    'no_alerts_description':
        'Your upcoming warranty deadlines will appear here.',
    'warranty_until': 'Warranty until',
    'account': 'Account',
    'my_account': 'My account',
    'notifications': 'Notifications',
    'help': 'Help',
    'free': 'FREE',
    'premium_badge': 'PREMIUM',
    'manage_subscription': 'Manage my subscription',
    'subscription': 'Subscription',
    'premium_title': 'Premium profile',
    'premium_active_status': 'Your subscription is active',
    'premium_status': 'Status:',
    'active': 'Active',
    'premium_member': 'Premium member',
    'premium_features_list_title': 'Your Premium benefits',
    'feat_unlimited_tickets': 'Unlimited tickets',
    'feat_export': 'PDF/CSV export',
    'feat_reminders': 'Warranty reminders',
    'feat_warranty': 'Warranty extension',
    'current_plan': 'Current plan',
    'version_page_title': 'App version',
    'app_info_description':
        'TicketScan helps you keep your tickets and warranties in one place.',
    'support_title': 'Contact support',
    'support_description': 'A question or an issue? Our team answers by email.',
    'write_us': 'Write to us',
    'tickets_short': 'My tickets',
    'pdf_warranty_certificate': 'WARRANTY CERTIFICATE',
    'pdf_store': 'Store',
    'pdf_purchase_date': 'Purchase date',
    'pdf_category': 'Category',
    'pdf_total_amount': 'TOTAL AMOUNT',
    'pdf_warranty_valid_until': 'WARRANTY VALID UNTIL:',
    'pdf_items_detail': 'ITEM DETAILS',
    'pdf_warrantied': 'Warrantied',
    'pdf_purchase_proof': 'PROOF OF PURCHASE (PHOTO)',
    'pdf_footer':
        'Document generated by the TicketScan app - Keep your purchase proofs safe.',
    'pdf_preview': 'PDF Preview',
  };

  String get(String key) {
    Map<String, String> translations = (locale.languageCode == 'en')
        ? _en
        : _fr;
    return translations[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();
  @override
  bool isSupported(Locale locale) => ['en', 'fr'].contains(locale.languageCode);
  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);
  @override
  bool shouldReload(LocalizationsDelegate<AppLocalizations> old) => false;
}
