// lib/core/services/offline_hash_queue.dart
import 'package:hive/hive.dart';
import 'package:crypto/crypto.dart';
import 'package:flutter/foundation.dart'; // for debugPrint
import 'supabase_service.dart';

part 'offline_hash_queue.g.dart'; // generated by hive generator

@HiveType(typeId: 0)
class HashQueueItem {
  @HiveField(0)
  final String filePath; // chemin du PNG dont on veut stocker le hash
  @HiveField(1)
  final String hashHex;  // hash pré‑calculé (évite de le recomputer à chaque retry)
  @HiveField(2)
  final DateTime queuedAt;

  HashQueueItem({
    required this.filePath,
    required this.hashHex,
    required this.queuedAt,
  });
}

// ---------- Initialisation ----------
Future<void> initHashQueue() async {
  await Hive.initFlutter();
  Hive.registerAdapter(HashQueueItemAdapter());
  await Hive.openBox<HashQueueItem>('hashQueue');
}

// ---------- Enregistrement d’un hash en attente ----------
Future<void> enqueueHash(String filePath, String hashHex) async {
  final box = Hive.box<HashQueueItem>('hashQueue');
  await box.add(HashQueueItem(
    filePath: filePath,
    hashHex: hashHex,
    queuedAt: DateTime.now(),
  ));
}

// ---------- Traitement de la file d’attente ----------
Future<void> processHashQueue() async {
  final box = Hive.box<HashQueueItem>('hashQueue');
  final items = box.keys.toList(); // Get keys to iterate
  for (final key in items) {
    final item = box.get(key);
    if (item != null) {
      try {
        await SupabaseService.storeHash(item.hashHex);
        await box.delete(key); // succès → suppression
      } catch (e) {
        // Échec → on garde l’item pour un nouveau retry plus tard
        debugPrint('Hash‑queue retry failed: $e');
      }
    }
  }
}