SET local check_function_bodies = off;

CREATE EXTENSION "pg_cron";

CREATE TABLE "public"."app_config" (
  "id"                   bigint  GENERATED ALWAYS AS IDENTITY NOT NULL,
  "min_version"          text    NOT NULL DEFAULT '1.0.0'::text,
  "update_url"           text,
  "is_under_maintenance" boolean DEFAULT false,
  CONSTRAINT "app_config_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."app_config"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."apple_notifications_log" (
  "id"                      uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "notification_type"       text,
  "subtype"                 text,
  "original_transaction_id" text,
  "environment"             text,
  "processed_ok"            boolean                  NOT NULL DEFAULT true,
  "error_message"           text,
  "received_at"             timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "apple_notifications_log_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."apple_notifications_log"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."profiles" (
  "id"               uuid                     NOT NULL,
  "is_premium"       boolean                  DEFAULT false,
  "scans_this_month" integer                  DEFAULT 0,
  "updated_at"       timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "profiles_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."profiles"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."scan_logs" (
  "id"            uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "user_id"       uuid                     NOT NULL,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "accepted"      boolean                  NOT NULL,
  "reject_reason" text,
  "confidence"    numeric,
  "images_count"  smallint,
  CONSTRAINT "scan_logs_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."scan_logs"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."subscriptions" (
  "id"                      uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "user_id"                 uuid                     NOT NULL,
  "platform"                text                     NOT NULL,
  "product_id"              text                     NOT NULL,
  "original_transaction_id" text                     NOT NULL,
  "status"                  text                     NOT NULL,
  "expires_at"              timestamp with time zone NOT NULL,
  "auto_renew"              boolean                  NOT NULL DEFAULT false,
  "environment"             text,
  "last_verified_at"        timestamp with time zone NOT NULL DEFAULT now(),
  "created_at"              timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"              timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "subscriptions_pkey" PRIMARY KEY (id),
  CONSTRAINT "subscriptions_platform_check" CHECK ((platform = ANY (ARRAY['ios'::text, 'android'::text]))),
  CONSTRAINT "subscriptions_platform_original_transaction_id_key" UNIQUE (platform, original_transaction_id),
  CONSTRAINT "subscriptions_status_check" CHECK ((status = ANY (ARRAY['active'::text, 'grace_period'::text, 'billing_retry'::text, 'expired'::text, 'revoked'::text])))
);

ALTER TABLE "public"."subscriptions"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."ticket_hashes" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"    uuid                     NOT NULL,
  "hash"       text                     NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "ticket_hashes_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."ticket_hashes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."tickets" (
  "id"                uuid                        NOT NULL DEFAULT gen_random_uuid(),
  "user_id"           uuid,
  "store_name"        text,
  "date"              timestamp without time zone,
  "total_amount"      numeric,
  "products"          text[],
  "warranty_end_date" timestamp without time zone,
  "extracted_text"    text[],
  "created_at"        timestamp without time zone DEFAULT now(),
  "category"          text                        DEFAULT 'Autre'::text,
  "store_address"     text,
  "currency"          text                        DEFAULT '€'::text,
  "image_urls"        jsonb,
  "hash_proofs"       jsonb                       NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT "tickets_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."tickets"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.delete_expired_tickets()
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  AS $function$
begin
  delete from public.tickets
  where warranty_end_date < now();
end;
$function$;

CREATE OR REPLACE FUNCTION public.expire_premium()
  RETURNS void
  LANGUAGE sql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
  update public.profiles p
  set is_premium = false
  where p.is_premium
    and exists (select 1 from public.subscriptions s where s.user_id = p.id)
    and not exists (
      select 1 from public.subscriptions s
      where s.user_id = p.id
        and s.status in ('active', 'grace_period')
        and s.expires_at > now()
    );
$function$;

REVOKE ALL ON FUNCTION "public"."expire_premium"() FROM PUBLIC, "anon", "authenticated";

CREATE OR REPLACE FUNCTION public.handle_new_user()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  AS $function$
begin
  insert into public.profiles (id)
  values (new.id);
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.refresh_premium (
  p_user uuid
)
  RETURNS void
  LANGUAGE sql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
  update public.profiles
  set is_premium = exists (
    select 1 from public.subscriptions s
    where s.user_id = p_user
      and s.status in ('active', 'grace_period')
      and s.expires_at > now()
  )
  where id = p_user;
$function$;

REVOKE ALL ON FUNCTION "public"."refresh_premium"(uuid) FROM PUBLIC, "anon", "authenticated";

CREATE OR REPLACE FUNCTION public.trg_subscriptions_refresh()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
begin
  perform public.refresh_premium(coalesce(new.user_id, old.user_id));
  return null;
end;
$function$;

REVOKE ALL ON FUNCTION "public"."trg_subscriptions_refresh"() FROM PUBLIC, "anon", "authenticated";

ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."scan_logs"
  ADD CONSTRAINT "scan_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."subscriptions"
  ADD CONSTRAINT "subscriptions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."ticket_hashes"
  ADD CONSTRAINT "ticket_hashes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);

ALTER TABLE "public"."tickets"
  ADD CONSTRAINT "tickets_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX idx_ticket_hashes_created_at ON public.ticket_hashes USING btree (created_at);

CREATE INDEX idx_ticket_hashes_hash ON public.ticket_hashes USING btree (hash);

CREATE INDEX idx_ticket_hashes_user_id ON public.ticket_hashes USING btree (user_id);

CREATE INDEX scan_logs_user_created_idx ON public.scan_logs USING btree (user_id, created_at DESC);

CREATE INDEX subscriptions_expires_idx ON public.subscriptions USING btree (status, expires_at);

CREATE INDEX subscriptions_user_idx ON public.subscriptions USING btree (user_id);

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

CREATE TRIGGER subscriptions_refresh
  AFTER INSERT OR DELETE OR UPDATE ON public.subscriptions
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_subscriptions_refresh();

CREATE POLICY "La config est lisible par tous" ON "public"."app_config"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Les utilisateurs peuvent modifier leur propre profil" ON "public"."profiles"
  FOR UPDATE
  TO PUBLIC
  USING ((auth.uid() = id));

CREATE POLICY "Les utilisateurs peuvent voir leur propre profil" ON "public"."profiles"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = id));

CREATE POLICY "insert own scan logs" ON "public"."scan_logs"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "select own scan logs" ON "public"."scan_logs"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "read own subscriptions" ON "public"."subscriptions"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "users can insert own ticket hashes" ON "public"."ticket_hashes"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "users can read own ticket hashes" ON "public"."ticket_hashes"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can delete their own tickets" ON "public"."tickets"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can insert their own tickets" ON "public"."tickets"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can update their own tickets" ON "public"."tickets"
  FOR UPDATE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can view their own tickets" ON "public"."tickets"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can upload their own ticket images" ON "storage"."objects"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (((bucket_id = 'tickets'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));

CREATE POLICY "Users can view their own ticket images" ON "storage"."objects"
  FOR SELECT
  TO PUBLIC
  USING (((bucket_id = 'tickets'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));

CREATE POLICY "upload_ticket_img" ON "storage"."objects"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((bucket_id = 'tickets'::text));

COMMENT ON EXTENSION "pg_cron" IS 'Job scheduler for PostgreSQL';

GRANT EXECUTE ON FUNCTION "public"."delete_expired_tickets"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."expire_premium"() TO "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."handle_new_user"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."refresh_premium"(uuid) TO "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."trg_subscriptions_refresh"() TO "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."app_config" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."apple_notifications_log" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."scan_logs" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."subscriptions" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."ticket_hashes" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."tickets" TO "anon", "authenticated", "postgres", "service_role";

SELECT cron.schedule_in_database('expire-premium', '*/15 * * * *', 'select public.expire_premium()', 'postgres', NULL, true);

SELECT
  cron.schedule_in_database('purge-apple-notifications-log', '0 3 * * *', 'delete from public.apple_notifications_log where received_at < now() - interval ''90 days''', 'postgres',
  NULL, true);

